### PR TITLE
[FRONT PAGE] Caption Nomination Digital Press

### PR DESCRIPTION
**Pull request by dyligently**
Pick a caption! I'm also open to suggestion concerning matters in composing **caption** (longer) or **tagline** (shorter yet memorable!) for our dear **Digital Press** front page. It doesn't have to be eye-candy but it surely must reflect the mission and the contents we provide. If none of these captions deemed unsuitable, drop your ideas or comments that may stimulate me generating new captions!

1. In the constant motion of spreading knowledge and encircling the academic community 

2. Enlightening and simplifying science trends

3. The cornerstone of interdisciplinary scientific proceedings and books

4. For the fulfillment of academic inclusivity

5. Committed to establishing a learned society in a whole array of the field of studies

6. A mission-driven scientific community at Universitas Gadjah Mada

7. Curating brilliant proceedings and books generated from big ideas 

8. Curating big themes from a vast scientific field of studies through proceedings and books

9. Delivering thoughtful research ideas through proceedings and books

10. Accommodating a path towards scientific deep understanding through proceedings and books

### CODE REVIEW

**Comment by w1lldone** [comment]
I choose  
### The cornerstone of interdisciplinary scientific proceedings and books

**Comment by dyligently** [comment]
> I choose
> 
> ### The cornerstone of interdisciplinary scientific proceedings and books

Yish!! Done!

**Comment by w1lldone** [comment]
You can also make your personal choice @dyligently, @ulfaintania. Don't forget to ask Nopi. She doesn't have to make github account. We can ask her directly and put the answer here for the record.

**Comment by dyligently** [comment]
In the constant motion of spreading knowledge and encircling the academic community

**Comment by dyligently** [comment]
Enlightening and simplifying science trends

**Comment by dyligently** [comment]
The cornerstone of interdisciplinary scientific proceedings and books

**Comment by dyligently** [comment]
For the fulfillment of academic inclusivity

**Comment by dyligently** [comment]
Committed to establishing a learned society in a whole array of the field of studies

**Comment by dyligently** [comment]
A mission-driven scientific community at Universitas Gadjah Mada

**Comment by dyligently** [comment]
Curating brilliant proceedings and books generated from big ideas

Curating big themes from a vast scientific field of studies through proceedings and books

Delivering thoughtful research ideas through proceedings and books

Accommodating a path towards scientific deep understanding through proceedings and books

**Comment by dyligently** [comment]
Delivering thoughtful research ideas through proceedings and books

Accommodating a path towards scientific deep understanding through proceedings and books

**Comment by dyligently** [comment]
Accommodating a path towards scientific deep understanding through proceedings and books

**Comment by dyligently** [comment]
Curating big themes from a vast scientific field of studies through proceedings and books

**Comment by w1lldone** [comment]
> Curating brilliant proceedings and books generated from big ideas
> 
> Curating big themes from a vast scientific field of studies through proceedings and books
> 
> Delivering thoughtful research ideas through proceedings and books
> 
> Accommodating a path towards scientific deep understanding through proceedings and books

Duplicates

**Pull request merged**
